# OOP IN PYTHON
# TO MAP WITH REAL WORLD SCENARIOS, WE STARTED USING OBJECTS IN CODE. THIS IS CALLED OBJECT ORIENTED PROGRAMMING.

# CLASSES AND OBJECTS
# CLASS IS A BLUEPRINT FOR CREATING OBJECTS.

# CREATING CLASS
class Car:
    color = "blue"
    brand = "mercedes"

# CREATING OBJECT (INSTANCE)
c1 = Car()
print(c1.color)
print(c1.brand)
