# FUNCTIONS IN PYTHON
# BLOCK OF STATEMENTS THAT PERFORM A SPECIFIC TASK.
# FUNCTIONS ARE USED TO PREVENT FROM REDUNDANCY.

# FUNCTION DEFINITION
def calc_sum(a,b):                # a AND b ARE PARAMETERS
    sum = a + b
    return sum

# FUNCTION CALL
print("SUM :",calc_sum(5,4))      # 5 AND 4 ARE ARGUMENTS (ACTUAL VALUES)
