# STATIC METHODS
# METHODS THAT DON'T USE THE self PARAMETER (WORKS AT THE CLASS LEVEL).

class Student:
    @staticmethod      # DECORATOR
    def hello():
        print("HELLO")

s1 = Student()
s1.hello()

# DECORATORS ALLOW US TO WRAP ANOTHER FUNCTION IN ORDER TO EXTEND THE BEHAVIOR OF WRAPPED FUNCTION,
# WITHOUT PERMANENTLY MODIFYING IT.
