#WRITE A PROGRAM TO CHECK IF A NUMBER ENTERED BY THE USER IS A MULTIPLE OF 7 OR NOT.

num = int(input("ENTER ANY NUMBER : "))
if(num%7 == 0):
    print("YES!NUMBER IS A MULTIPLE OF 7")
else:
    print("NO! NUMBER IS NOT A MULTIPLE OF 7")
