# CREATE A NEW FILE "practice.txt" USING PYTHON. ADD THE FOLLOWING DATA IN IT:
# HI EVERYONE
# WE ARE LEARNING FILE I/O
# USING JAVA.
# I LIKE PROGRAMMING IN JAVA.

f = open("practice.txt","w")
f.write("HI EVERYONE\nWE ARE LEARNING FILE I/O\nUSING JAVA.\nI LIKE PROGRAMMING IN JAVA.")
f.close()
