# YOU ARE GIVEN A LIST OF SUBJECTS FOR STUDENTS. ASSUME 1 CLASSROOM IS REQUIRED FOR 1 SUBJECT. 
# HOW MANY CLASSROOMS ARE NEEDED BY ALL STUDENTS. 
# "PYTHON", "JAVA", "C++", "PYTHON", "JAVASCRIPT", "JAVA", "PYTHON", "JAVA", "C++", "C"

subjects = {"PYTHON", "JAVA", "C++", "PYTHON", "JAVASCRIPT", "JAVA", "PYTHON", "JAVA", "C++", "C"}
print("TOTAL NO. OF CLASSROOMS REQUIRED FOR STUDENTS :", len(subjects))
